import { Toaster } from '$/components/ui/toaster';
import type { Metadata } from 'next';
import { Header } from './_header';

import './globals.css';

export const metadata: Metadata = {
	title: 'Supply Tracker',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en'>
			<body className='bg-white'>
				{/* <Header /> */}
				{children}
				<Toaster />
			</body>
		</html>
	);
}
