import type { Metadata } from 'next';

import './globals.css';
import { ClientProviders } from './_providers';

export const metadata: Metadata = {
	title: 'Supply Tracker',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className='bg-slate-100'>
				<ClientProviders>{children}</ClientProviders>
			</body>
		</html>
	);
}
